CREATE TABLE DIAL_CODES (
	DIAL_CODE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	DIAL_CODE INTEGER NOT NULL,
	CONSTRAINT PK_DIAL_CODE PRIMARY KEY (DIAL_CODE_ID)
);

INSERT INTO DIAL_CODES(DIAL_CODE) VALUES(22);
INSERT INTO DIAL_CODES(DIAL_CODE) VALUES(12);

