CREATE TABLE ADDRESSES
(
    ADDRESS_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    STREET VARCHAR(255),
    `NUMBER` VARCHAR(64),
    CITY VARCHAR(255) NOT NULL,
    PHONE VARCHAR(16),
    DIAL_CODE_ID BIGINT(20),
    CONSTRAINT PK_ADDRESS PRIMARY KEY (ADDRESS_ID),
    CONSTRAINT FK_ADDRESS_DIAL_CODE FOREIGN KEY (DIAL_CODE_ID) REFERENCES dial_codes(DIAL_CODE_ID)
);

CREATE TABLE CLIENTS
(
	CLIENT_ID  BIGINT(20)   NOT NULL AUTO_INCREMENT,
	FORENAME   VARCHAR(128),
	LASTNAME   VARCHAR(128) NOT NULL,
	ADDRESS_ID BIGINT(20)   NOT NULL,
	CONSTRAINT PK_CLIENT PRIMARY KEY (CLIENT_ID),
	CONSTRAINT FK_CLIENT_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES (ADDRESS_ID)
);

CREATE TABLE ORDERS
(
    ORDER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    QUANTITY INTEGER NOT NULL,
    CLIENT_ID BIGINT(20) NOT NULL,
    CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDER_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
);