CREATE TABLE GREETER (
    GREETER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    GREETING_ID BIGINT(20) NOT NULL,
    CONSTRAINT PK_GREETER PRIMARY KEY (GREETER_ID),
    CONSTRAINT FK_GREETER_GREETING FOREIGN KEY (GREETING_ID) REFERENCES greetings(GREETING_ID)
);